### ISSUE TITLE
Bad generation results on "stabilityai/stable-diffusion-2-1"

### ISSUE THREAD

**Issue by Maguire1999** [KAIST-Geometric-AI-Group/SyncDiffusion#2]
Hello, I use the "stabilityai/stable-diffusion-2-1" as diffusion model . Specifically, I have tried using the DPMSolverMultistepScheduler and DDIMScheduler , but both get the bad results.

**Comment by Maguire1999** [comment]
![sync1](https://github.com/KAIST-Geometric-AI-Group/SyncDiffusion/assets/57634227/1cc8ca4e-b7ad-4375-9005-1e4368774c6c)
![sync](https://github.com/KAIST-Geometric-AI-Group/SyncDiffusion/assets/57634227/125025c4-bf4b-4827-bf46-266108f6b2a9)

**Comment by phillipinseoul** [comment]
Hi, thanks for your interest in our work.

As our work is based on the 512x512 versions of Stable Diffusion, it is recommended to use the "stabilityai/stable-diffusion-2-1-base" as in the code, which uses a 64x64 sized latent. 

The bad generations are possibly caused by trying to generate a 512x1024 with "stabilityai/stable-diffusion-2-1", which produces 768x768 images and uses 96x96 latent. 

You can still use our code for this model by setting the resolution accordingly (e.g. 768x896) and changing the "latent_size" to 96. However, note that `torch.autocast` may not work in stable-diffusion-2-1 as explained in https://github.com/huggingface/diffusers/issues/1614#issuecomment-1385093065.
